### ISSUE TITLE
Can't make it work

### ISSUE THREAD

**Issue by vadimvitvickiy** [maquannene/Track#8]
Hello, i'm trying cache images with DiskCache, but when i try to read nothing is returned
`diskCache.set(object: cache, forKey: "\(step)") { (cache, key, object) in
            debugPrint(self.diskCache["\(self.step)"] ?? "")
        }`
console prints ""

**Comment by maquannene** [comment]
can you provide the commit number you use？
I  fix a problem about save path  recently .
https://github.com/maquannene/Track/commit/24e1f88f2344182f6dad0f275a08ac4fff9b2fd9
you can have a try.

**Comment by aasatt** [comment]
The issues is with `_createCacheDir()` in `DiskCache.swift`

Update to use `cacheURL.path` instead of the raw string. 
`FileManager.default.createDirectory(atPath: cacheURL.path, withIntermediateDirectories: true, attributes: nil)`

More info here: 
https://stackoverflow.com/questions/32659869/ios9-swift-file-creating-nsfilemanager-createdirectoryatpath-with-nsurl
